In [1]:
import numpy as np

In [15]:
# Create 2D array with random integer elements
arr = np.random.randint(100, size=32).reshape(8, 4)
arr

array([[38, 86, 88, 89],
       [77, 73, 92,  4],
       [31, 76, 81, 84],
       [44, 31, 92, 77],
       [66, 62, 45, 16],
       [88, 80,  0, 77],
       [66, 64, 90, 73],
       [57, 84, 43, 60]])

In [16]:
np.sort(arr)

array([[38, 86, 88, 89],
       [ 4, 73, 77, 92],
       [31, 76, 81, 84],
       [31, 44, 77, 92],
       [16, 45, 62, 66],
       [ 0, 77, 80, 88],
       [64, 66, 73, 90],
       [43, 57, 60, 84]])

In [17]:
np.sort(arr)[:, ::-1]

array([[89, 88, 86, 38],
       [92, 77, 73,  4],
       [84, 81, 76, 31],
       [92, 77, 44, 31],
       [66, 62, 45, 16],
       [88, 80, 77,  0],
       [90, 73, 66, 64],
       [84, 60, 57, 43]])

In [24]:
somearr = np.array([1, 2, 3, 4, 5])

h = np.tile(somearr, (2, 2))
h

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [30]:
np.shares_memory(somearr, somearr+1)

False

In [39]:
a = np.arange(1, 11)

b = a[a%1 == 0]


In [41]:
np.shares_memory(a, a.view())

True

In [43]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a.view()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.shares_memory(a, a.copy())

False

In [51]:
import copy
np.shares_memory(a.copy(), copy.deepcopy(a))

False

In [52]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr0 = a.view()

In [57]:
arr1 = a.copy()

In [58]:
arr2 = copy.deepcopy(a)

In [67]:
np.shares_memory(a, arr0)

True

In [68]:
arr = np.random.randint(100, size=32)
arr

array([36, 22, 39, 38, 73, 86, 10, 25, 63, 12, 82, 35, 69, 23, 56, 78, 74,
       14, 76, 70, 63, 61, 52, 64, 61, 76, 84, 18, 63, 35, 67, 34])

In [72]:
np.split(arr, [8, 4, -1])

[array([36, 22, 39, 38, 73, 86, 10, 25]),
 array([], dtype=int64),
 array([73, 86, 10, 25, 63, 12, 82, 35, 69, 23, 56, 78, 74, 14, 76, 70, 63,
        61, 52, 64, 61, 76, 84, 18, 63, 35, 67]),
 array([34])]

In [77]:
np.split(arr, [8, 4, -1])[2]

array([73, 86, 10, 25, 63, 12, 82, 35, 69, 23, 56, 78, 74, 14, 76, 70, 63,
       61, 52, 64, 61, 76, 84, 18, 63, 35, 67])

In [78]:
arr.reshape(4, 8)

array([[36, 22, 39, 38, 73, 86, 10, 25],
       [63, 12, 82, 35, 69, 23, 56, 78],
       [74, 14, 76, 70, 63, 61, 52, 64],
       [61, 76, 84, 18, 63, 35, 67, 34]])

In [81]:
np.vsplit(arr.reshape(4, 8), 4)

[array([[36, 22, 39, 38, 73, 86, 10, 25]]),
 array([[63, 12, 82, 35, 69, 23, 56, 78]]),
 array([[74, 14, 76, 70, 63, 61, 52, 64]]),
 array([[61, 76, 84, 18, 63, 35, 67, 34]])]

In [82]:
np.hsplit(arr.reshape(4, 8), 4)

[array([[36, 22],
        [63, 12],
        [74, 14],
        [61, 76]]),
 array([[39, 38],
        [82, 35],
        [76, 70],
        [84, 18]]),
 array([[73, 86],
        [69, 23],
        [63, 61],
        [63, 35]]),
 array([[10, 25],
        [56, 78],
        [52, 64],
        [67, 34]])]

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [2]:
arr = np.random.randint(20, size=64).reshape(8, 8)
arr

array([[17,  4,  4,  8,  9,  1,  7,  9],
       [ 6, 18,  7, 11,  8, 12,  8, 14],
       [ 0,  3,  7, 14, 13, 11,  4, 10],
       [19, 18,  5, 13, 19, 12,  1,  6],
       [13, 11, 10, 10, 17,  0, 16,  5],
       [11, 12,  8, 18, 18,  6, 12,  4],
       [ 9, 14,  4,  9, 14,  4, 13, 17],
       [12, 15, 10, 13,  9, 13,  9, 15]])

In [3]:
np.hsplit(arr, [3, 5, 6, ])

[array([[17,  4,  4],
        [ 6, 18,  7],
        [ 0,  3,  7],
        [19, 18,  5],
        [13, 11, 10],
        [11, 12,  8],
        [ 9, 14,  4],
        [12, 15, 10]]),
 array([[ 8,  9],
        [11,  8],
        [14, 13],
        [13, 19],
        [10, 17],
        [18, 18],
        [ 9, 14],
        [13,  9]]),
 array([[ 1],
        [12],
        [11],
        [12],
        [ 0],
        [ 6],
        [ 4],
        [13]]),
 array([[ 7,  9],
        [ 8, 14],
        [ 4, 10],
        [ 1,  6],
        [16,  5],
        [12,  4],
        [13, 17],
        [ 9, 15]])]

In [4]:
np.vsplit(arr, [3, 5, 6, ])

[array([[17,  4,  4,  8,  9,  1,  7,  9],
        [ 6, 18,  7, 11,  8, 12,  8, 14],
        [ 0,  3,  7, 14, 13, 11,  4, 10]]),
 array([[19, 18,  5, 13, 19, 12,  1,  6],
        [13, 11, 10, 10, 17,  0, 16,  5]]),
 array([[11, 12,  8, 18, 18,  6, 12,  4]]),
 array([[ 9, 14,  4,  9, 14,  4, 13, 17],
        [12, 15, 10, 13,  9, 13,  9, 15]])]

In [5]:
np.split(arr, [3, 5, 6], axis=0) 

[array([[17,  4,  4,  8,  9,  1,  7,  9],
        [ 6, 18,  7, 11,  8, 12,  8, 14],
        [ 0,  3,  7, 14, 13, 11,  4, 10]]),
 array([[19, 18,  5, 13, 19, 12,  1,  6],
        [13, 11, 10, 10, 17,  0, 16,  5]]),
 array([[11, 12,  8, 18, 18,  6, 12,  4]]),
 array([[ 9, 14,  4,  9, 14,  4, 13, 17],
        [12, 15, 10, 13,  9, 13,  9, 15]])]

In [6]:
arr = np.random.randint(10, size=168).reshape(3,7,8)
arr

array([[[9, 4, 4, 8, 1, 0, 7, 1],
        [1, 7, 3, 3, 6, 0, 2, 7],
        [6, 7, 4, 5, 4, 1, 6, 8],
        [6, 3, 2, 5, 7, 4, 1, 6],
        [3, 2, 0, 1, 3, 0, 5, 9],
        [6, 2, 1, 9, 6, 6, 6, 6],
        [9, 2, 7, 0, 9, 8, 2, 1]],

       [[3, 5, 0, 3, 4, 3, 6, 7],
        [4, 7, 6, 5, 8, 1, 2, 4],
        [2, 2, 3, 3, 3, 7, 4, 9],
        [8, 9, 3, 1, 3, 9, 5, 0],
        [9, 5, 9, 1, 9, 0, 9, 2],
        [6, 1, 3, 1, 4, 6, 3, 0],
        [9, 9, 5, 8, 3, 7, 1, 4]],

       [[0, 6, 4, 6, 7, 3, 4, 9],
        [8, 2, 2, 6, 5, 0, 0, 7],
        [5, 4, 9, 0, 9, 4, 3, 4],
        [1, 2, 2, 7, 4, 0, 6, 3],
        [8, 2, 0, 3, 6, 0, 8, 8],
        [8, 9, 6, 7, 9, 7, 7, 7],
        [8, 1, 9, 0, 1, 6, 7, 4]]])

In [37]:
np.dsplit(arr, 7)

ValueError: array split does not result in an equal division

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])

np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a = np.array([[1, 2, 3, 4, 6]])
b = np.array([[7, 8, 9, 10, 11, 12]])

np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12]])

In [53]:
rgen = np.random.default_rng()

arr_list = [rgen.integers(low=0, high=9, size=10).reshape(2, 5) for _ in range(8)]
arr_list

[array([[1, 2, 0, 5, 8],
        [7, 8, 3, 7, 1]]),
 array([[4, 2, 3, 8, 4],
        [7, 8, 6, 4, 2]]),
 array([[6, 6, 7, 2, 1],
        [8, 1, 5, 5, 3]]),
 array([[2, 2, 2, 6, 6],
        [4, 8, 3, 1, 5]]),
 array([[4, 3, 5, 0, 4],
        [0, 3, 1, 8, 3]]),
 array([[3, 0, 0, 2, 8],
        [1, 7, 8, 6, 7]]),
 array([[8, 2, 6, 4, 4],
        [0, 1, 7, 7, 3]]),
 array([[7, 3, 2, 2, 1],
        [7, 7, 0, 7, 2]])]

In [82]:
a = np.stack(arr_list, axis=1).T
a

array([[[1, 7],
        [4, 7],
        [6, 8],
        [2, 4],
        [4, 0],
        [3, 1],
        [8, 0],
        [7, 7]],

       [[2, 8],
        [2, 8],
        [6, 1],
        [2, 8],
        [3, 3],
        [0, 7],
        [2, 1],
        [3, 7]],

       [[0, 3],
        [3, 6],
        [7, 5],
        [2, 3],
        [5, 1],
        [0, 8],
        [6, 7],
        [2, 0]],

       [[5, 7],
        [8, 4],
        [2, 5],
        [6, 1],
        [0, 8],
        [2, 6],
        [4, 7],
        [2, 7]],

       [[8, 1],
        [4, 2],
        [1, 3],
        [6, 5],
        [4, 3],
        [8, 7],
        [4, 3],
        [1, 2]]])

In [85]:
np.stack(a, axis=0)


array([[[1, 7],
        [4, 7],
        [6, 8],
        [2, 4],
        [4, 0],
        [3, 1],
        [8, 0],
        [7, 7]],

       [[2, 8],
        [2, 8],
        [6, 1],
        [2, 8],
        [3, 3],
        [0, 7],
        [2, 1],
        [3, 7]],

       [[0, 3],
        [3, 6],
        [7, 5],
        [2, 3],
        [5, 1],
        [0, 8],
        [6, 7],
        [2, 0]],

       [[5, 7],
        [8, 4],
        [2, 5],
        [6, 1],
        [0, 8],
        [2, 6],
        [4, 7],
        [2, 7]],

       [[8, 1],
        [4, 2],
        [1, 3],
        [6, 5],
        [4, 3],
        [8, 7],
        [4, 3],
        [1, 2]]])

In [138]:
mat = np.random.default_rng().integers(low=0, high=9, size=8).reshape(4, 2)
mat

array([[4, 1],
       [1, 3],
       [1, 7],
       [5, 8]])

In [139]:
# vertical padding
padding = np.zeros(mat.shape[1], dtype='int')
mat = np.vstack([padding, mat, padding])
mat

array([[0, 0],
       [4, 1],
       [1, 3],
       [1, 7],
       [5, 8],
       [0, 0]])

In [140]:
# horizontal padding
padding = np.zeros(mat.shape[0], dtype='int').reshape(-1,1)
mat = np.hstack([padding, mat, padding])
mat




array([[0, 0, 0, 0],
       [0, 4, 1, 0],
       [0, 1, 3, 0],
       [0, 1, 7, 0],
       [0, 5, 8, 0],
       [0, 0, 0, 0]])

In [141]:
arr = np.random.randint(10, size=12)
arr

array([6, 6, 9, 7, 4, 4, 2, 3, 4, 9, 1, 8])

In [158]:
arr1 = arr[arr>0]
arr1

array([6, 6, 9, 7, 4, 4, 2, 3, 4, 9, 1, 8])

In [159]:
arr1.base is arr

False

In [163]:
mat.reshape(6,2,2)

array([[[0, 0],
        [0, 0]],

       [[0, 4],
        [1, 0]],

       [[0, 1],
        [3, 0]],

       [[0, 1],
        [7, 0]],

       [[0, 5],
        [8, 0]],

       [[0, 0],
        [0, 0]]])

In [165]:
mat.reshape(6,2,2)[3::]

array([[[0, 1],
        [7, 0]],

       [[0, 5],
        [8, 0]],

       [[0, 0],
        [0, 0]]])

In [168]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
np.hstack((arr, arr[:, 0].reshape(3,1)))

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])