In [1]:
import numpy as np

In [6]:
# Create 2D array with random integer elements
arr = np.random.randint(100, size=32).reshape(8, 4)
arr

array([[15, 10, 77, 62],
       [ 9, 41, 48, 87],
       [88, 52, 62, 97],
       [34, 90, 43, 29],
       [59, 11, 66, 68],
       [69, 60, 82, 28],
       [26, 20, 98, 93],
       [14, 30, 92, 62]])

In [7]:
# sort
np.sort(arr)

array([[10, 15, 62, 77],
       [ 9, 41, 48, 87],
       [52, 62, 88, 97],
       [29, 34, 43, 90],
       [11, 59, 66, 68],
       [28, 60, 69, 82],
       [20, 26, 93, 98],
       [14, 30, 62, 92]])

In [8]:
# reverse sort
np.sort(arr)[:, ::-1]

array([[77, 62, 15, 10],
       [87, 48, 41,  9],
       [97, 88, 62, 52],
       [90, 43, 34, 29],
       [68, 66, 59, 11],
       [82, 69, 60, 28],
       [98, 93, 26, 20],
       [92, 62, 30, 14]])

In [49]:
# Create 2D array with random integer elements
# arr = np.random.randint(10, size=8)
arr = np.array([10, 20, 30, 40])
arr

array([10, 20, 30, 40])

In [59]:
arr2 = arr.T
arr2

array([10, 20, 30, 40])

In [40]:
arr + arr2

array([ 9,  6,  3,  6,  8, 10,  7,  3])

In [51]:
g = np.tile(arr.reshape(2,2), (2,1))
g

array([[10, 20],
       [30, 40],
       [10, 20],
       [30, 40]])

In [55]:
h = np.tile(arr.reshape(4,1),(1,2))
h

array([[10, 10],
       [20, 20],
       [30, 30],
       [40, 40]])

In [56]:
g+h

array([[20, 30],
       [50, 60],
       [40, 50],
       [70, 80]])

In [69]:
arr + np.array([10, 20, 30, 40])

array([20, 40, 60, 80])